# Generated by Django 4.2.1 on 2025-05-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagproduct',
            old_name='tag',
            new_name='name',
        ),
    ]
